# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms\autoresationForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(200, 130)
        self.singinButton = QtWidgets.QPushButton(Dialog)
        self.singinButton.setGeometry(QtCore.QRect(40, 90, 111, 31))
        self.singinButton.setObjectName("singinButton")
        self.inputLogin = QtWidgets.QLineEdit(Dialog)
        self.inputLogin.setGeometry(QtCore.QRect(10, 10, 181, 31))
        self.inputLogin.setObjectName("inputLogin")
        self.inputPassword = QtWidgets.QLineEdit(Dialog)
        self.inputPassword.setGeometry(QtCore.QRect(10, 50, 181, 31))
        self.inputPassword.setObjectName("inputPassword")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Авторизация"))
        self.singinButton.setText(_translate("Dialog", "Войти"))
        self.inputLogin.setInputMask(_translate("Dialog", "Логин"))
        self.inputPassword.setInputMask(_translate("Dialog", "Пароль"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
